In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime

In [2]:
df=pd.read_csv("kothrud.csv")
df

,Sr. No,Sample ID,Unnamed: 2,Date,Location,Kit used,CtN,CtE,CtRdRp,PCR Result
0,1.0,SSBS/M/2021/1,S-1,04-10-2021,Sanjeevan hospital Kothrud,Genepath,0.0000,0.0000,0.000,Negative
1,2.0,SSBS/M/2021/2,S-2,04-10-2021,Kothrud Bus depot,Genepath,0.0000,0.0000,0.000,Negative
2,3.0,SSBS/M/2021/3,S-3,04-10-2021,Karve road Kothrud,Genepath,0.0000,0.0000,0.000,Negative
3,29.0,SSBS/M/2021/29,S-29,11-10-2021,Sanjeevan hospital Kothrud,Genepath,34.6000,35.8000,35.300,Positive
4,30.0,SSBS/M/2021/30,S-30,11-10-2021,Karve road Kothrud,Genepath,0.0000,34.5000,35.700,Positive
...,...,...,...,...,...,...,...,...,...,...
141,1245.0,SSBS/M/2022/1245,S-1245,12-09-2022,Kothrud Bus depot,Genepath,28.1545,38.9556,31.398,Positive
142,1265.0,SSBS/M/2022/1265,S-1265,19-09-2022,Karve road Kothrud,Genepath,0.0000,0.0000,0.000,Negative
143,1267.0,SSBS/M/2022/1267,S-1267,19-09-2022,Kothrud Bus depot,Genepath,0.0000,0.0000,0.000,Negative
144,1287.0,SSBS/M/2022/1287,S-1287,26-09-2022,Karve road Kothrud,Genepath,0.0000,0.0000,30.800,Negative
145,1289.0,SSBS/M/2022/1289,S-1289,26-09-2022,Kothrud Bus depot,Genepath,0.0000,0.0000,0.000,Negative

In [3]:
df=df.drop(['Sample ID','Unnamed: 2','Sr. No'],axis=1)

In [5]:
df

,Date,Location,Kit used,CtN,CtE,CtRdRp,PCR Result
0,04-10-2021,Sanjeevan hospital Kothrud,Genepath,0.0000,0.0000,0.000,Negative
1,04-10-2021,Kothrud Bus depot,Genepath,0.0000,0.0000,0.000,Negative
2,04-10-2021,Karve road Kothrud,Genepath,0.0000,0.0000,0.000,Negative
3,11-10-2021,Sanjeevan hospital Kothrud,Genepath,34.6000,35.8000,35.300,Positive
4,11-10-2021,Karve road Kothrud,Genepath,0.0000,34.5000,35.700,Positive
...,...,...,...,...,...,...,...
141,12-09-2022,Kothrud Bus depot,Genepath,28.1545,38.9556,31.398,Positive
142,19-09-2022,Karve road Kothrud,Genepath,0.0000,0.0000,0.000,Negative
143,19-09-2022,Kothrud Bus depot,Genepath,0.0000,0.0000,0.000,Negative
144,26-09-2022,Karve road Kothrud,Genepath,0.0000,0.0000,30.800,Negative
145,26-09-2022,Kothrud Bus depot,Genepath,0.0000,0.0000,0.000,Negative

In [6]:
print(df.dtypes)

Date           object
Location       object
Kit used       object
CtN           float64
CtE           float64
CtRdRp        float64
PCR Result     object
dtype: object

In [7]:
df['Date'] = df['Date'].astype(str)

In [8]:
df

,Date,Location,Kit used,CtN,CtE,CtRdRp,PCR Result
0,04-10-2021,Sanjeevan hospital Kothrud,Genepath,0.0000,0.0000,0.000,Negative
1,04-10-2021,Kothrud Bus depot,Genepath,0.0000,0.0000,0.000,Negative
2,04-10-2021,Karve road Kothrud,Genepath,0.0000,0.0000,0.000,Negative
3,11-10-2021,Sanjeevan hospital Kothrud,Genepath,34.6000,35.8000,35.300,Positive
4,11-10-2021,Karve road Kothrud,Genepath,0.0000,34.5000,35.700,Positive
...,...,...,...,...,...,...,...
141,12-09-2022,Kothrud Bus depot,Genepath,28.1545,38.9556,31.398,Positive
142,19-09-2022,Karve road Kothrud,Genepath,0.0000,0.0000,0.000,Negative
143,19-09-2022,Kothrud Bus depot,Genepath,0.0000,0.0000,0.000,Negative
144,26-09-2022,Karve road Kothrud,Genepath,0.0000,0.0000,30.800,Negative
145,26-09-2022,Kothrud Bus depot,Genepath,0.0000,0.0000,0.000,Negative

In [9]:
df

,Date,Location,Kit used,CtN,CtE,CtRdRp,PCR Result
0,04-10-2021,Sanjeevan hospital Kothrud,Genepath,0.0000,0.0000,0.000,Negative
1,04-10-2021,Kothrud Bus depot,Genepath,0.0000,0.0000,0.000,Negative
2,04-10-2021,Karve road Kothrud,Genepath,0.0000,0.0000,0.000,Negative
3,11-10-2021,Sanjeevan hospital Kothrud,Genepath,34.6000,35.8000,35.300,Positive
4,11-10-2021,Karve road Kothrud,Genepath,0.0000,34.5000,35.700,Positive
...,...,...,...,...,...,...,...
141,12-09-2022,Kothrud Bus depot,Genepath,28.1545,38.9556,31.398,Positive
142,19-09-2022,Karve road Kothrud,Genepath,0.0000,0.0000,0.000,Negative
143,19-09-2022,Kothrud Bus depot,Genepath,0.0000,0.0000,0.000,Negative
144,26-09-2022,Karve road Kothrud,Genepath,0.0000,0.0000,30.800,Negative
145,26-09-2022,Kothrud Bus depot,Genepath,0.0000,0.0000,0.000,Negative

In [10]:
print(df.dtypes)

Date           object
Location       object
Kit used       object
CtN           float64
CtE           float64
CtRdRp        float64
PCR Result     object
dtype: object

In [11]:
df["CtRdRp"]

0       0.000
1       0.000
2       0.000
3      35.300
4      35.700
        ...
141    31.398
142     0.000
143     0.000
144    30.800
145     0.000
Name: CtRdRp, Length: 146, dtype: float64

In [12]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Define the data set
date = df["Date"]
ctRdRp= df["CtRdRp"]

# Convert date strings to numeric values
date_num = np.arange(len(date))

# Reshape arrays to make them compatible with linear regression
date_num = date_num.reshape(-1, 1)
ctRdRp = np.array(ctRdRp).reshape(-1, 1)

# Create a linear regression model and fit it to the data
model = LinearRegression()
model.fit(date_num, ctRdRp)

# Print the coefficient
print('Linear regression coefficient: ', model.coef_[0][0])

Linear regression coefficient:  0.08750681653861356

In [13]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Define the data set
date = df["Date"]
ctn= df["CtN"]

# Convert date strings to numeric values
date_num = np.arange(len(date))

# Reshape arrays to make them compatible with linear regression
date_num = date_num.reshape(-1, 1)
ctn = np.array(ctn).reshape(-1, 1)

# Create a linear regression model and fit it to the data
model = LinearRegression()
model.fit(date_num, ctn)

# Print the coefficient
print('Linear regression coefficient: ', model.coef_[0][0])

Linear regression coefficient:  0.05548637559889331

In [14]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Define the data set
date = df["Date"]
cte= df["CtE"]

# Convert date strings to numeric values
date_num = np.arange(len(date))

# Reshape arrays to make them compatible with linear regression
date_num = date_num.reshape(-1, 1)
cte = np.array(cte).reshape(-1, 1)

# Create a linear regression model and fit it to the data
model = LinearRegression()
model.fit(date_num, cte)

# Print the coefficient
print('Linear regression coefficient: ', model.coef_[0][0])

Linear regression coefficient:  0.010737214194133017